/**
 ******************************************************************************
 * @addtogroup OpenPilotModules OpenPilot Modules
 * @{
 * @addtogroup SimulatedAttitude SimulatedAttitude Module
 * @brief Handles communication with AHRS and updating position
 * Specifically updates the the @ref AttitudeActual "AttitudeActual" and @ref AttitudeRaw "AttitudeRaw" settings objects
 * @{
 *
 * @file       simulatedattitude.c
 * @author     The OpenPilot Team, http://www.openpilot.org Copyright (C) 2010.
 * @brief      Module to handle all comms to the AHRS on a periodic basis.
 *
 * @see        The GNU Public License (GPL) Version 3
 *
 ******************************************************************************/
/*
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
 * or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
 * for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program; if not, write to the Free Software Foundation, Inc.,
 * 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
 */

/**
 * Input objects: As defined in PiOS/inc/pios_ahrs_comms.h
 * Output objects: As defined in PiOS/inc/pios_ahrs_comms.h
 *
 * This module will periodically update the values of latest attitude solution
 * and other objects that are transferred to and from the AHRS
 * The module settings can configure how often AHRS is polled for a new solution.
 *
 * The module executes in its own thread.
 *
 * UAVObjects are automatically generated by the UAVObjectGenerator from
 * the object definition XML file.
 *
 * Modules have no API, all communication to other modules is done through UAVObjects.
 * However modules may use the API exposed by shared libraries.
 * See the OpenPilot wiki for more details.
 * http://www.openpilot.org/OpenPilot_Application_Architecture
 *
 */

#include "simulatedattitude.h"
#include "pios.h"
#include "CoordinateConversions.h"
#include "attituderaw.h"
#include "attitudeactual.h"
#include "actuatorcommand.h"

// Private constants
#define STACK_SIZE configMINIMAL_STACK_SIZE-128
#define TASK_PRIORITY (tskIDLE_PRIORITY+4)

// Private types

// Private variables
static xTaskHandle taskHandle;

// Private functions
static void SimulatedAttitudeTask(void *parameters);

/**
 * Initialise the module, called on startup
 * \returns 0 on success or -1 if initialisation failed
 */
int32_t SimulatedAttitudeStart(void)
{
	// Start main task
	xTaskCreate(SimulatedAttitudeTask, (signed char *)"AHRSComms", STACK_SIZE, NULL, TASK_PRIORITY, &taskHandle);
	TaskMonitorAdd(TASKINFO_RUNNING_AHRSCOMMS, taskHandle);
	//PIOS_WDG_RegisterFlag(PIOS_WDG_AHRS);

	return 0;
}

/**
 * Initialise the module, called on startup
 * \returns 0 on success or -1 if initialisation failed
 */
int32_t SimulatedAttitudeInitialize(void)
{
	if (PIOS_SIM_Init() != 0)
		return -1;

	return 0;
}
MODULE_INITCALL(SimulatedAttitudeInitialize, SimulatedAttitudeStart)

/**
 * Module thread, should not return.
 */
static void SimulatedAttitudeTask(void *parameters)
{
	portTickType lastSysTime;

	AlarmsSet(SYSTEMALARMS_ALARM_AHRSCOMMS, SYSTEMALARMS_ALARM_CRITICAL);

	AttitudeRawData attitudeRaw;
	AttitudeActualData attitudeActual;
	ActuatorCommandData actuatorCommand;

	lastSysTime = xTaskGetTickCount();
	while (1) {
		//PIOS_WDG_UpdateFlag(PIOS_WDG_AHRS);
		
		AttitudeRawGet(&attitudeRaw);
		AttitudeActualGet(&attitudeActual);
		ActuatorCommandGet(&actuatorCommand);
		
		// Store the actuator channels in the pios system.  Some gymnastics
        // to keep simulation using floats
        float Actuator[NELEMENTS(actuatorCommand.Channel)];
		PIOS_SIM_SetActuator(Actuator, NELEMENTS(actuatorCommand.Channel));
        for (uint8_t i = 0; i < NELEMENTS(actuatorCommand.Channel); i++)
            actuatorCommand.Channel[i] = Actuator[i];
        
		// Run model forward a step
	        PIOS_SIM_Step(0.001);

		// TODO: Run data through a parallel EKF

		// Get data out of simulation into UAVObjects
		PIOS_SIM_GetAccels(attitudeRaw.accels);
		PIOS_SIM_GetGyros(attitudeRaw.gyros);
		PIOS_SIM_GetAttitude(&attitudeActual.q1);

		// Convert into eueler degrees (makes assumptions about RPY
		// order)
		Quaternion2RPY(&attitudeActual.q1,&attitudeActual.Roll);
        
		printf( "%f %f %f %f\n", attitudeActual.q1, attitudeActual.q2, 
				attitudeActual.q3, attitudeActual.q4);

		// Store updates UAVOs
		AttitudeRawSet(&attitudeRaw);
		AttitudeActualSet(&attitudeActual);

		/* Wait for the next update interval */
		vTaskDelayUntil(&lastSysTime, 1 / portTICK_RATE_MS);

	}
}

/**
  * @}
  * @}
  */
