/**
******************************************************************************
* @addtogroup UAVObjects OpenPilot UAVObjects
* @brief Autogenerated files and functions processing UAV Objects on Arduino
*
* @file       UAVObjects.h
* @author     The OpenPilot Team, http://www.openpilot.org Copyright (C) 2011.
* @brief      Declaration of the UAVObjects. This file has been 
*             automatically generated by the UAVObjectGenerator.
* 
* @note       This is an automatically generated file.
*             DO NOT modify manually.
*
* @see        The GNU Public License (GPL) Version 3
*
*****************************************************************************/
/*
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
 * or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
 * for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program; if not, write to the Free Software Foundation, Inc.,
 * 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
 */

/*
 * Modify this defines according to your application requirements.
 * Particularly if you do not need object names - do not include them
 * into the generated file and save a lot of flash and RAM (because
 * avr-gcc puts constants to the flash and copies them into RAM during
 * startup). This might be changed later to keep them in flash and use
 * PROGMEM modifier to access object names.
 */
//#define UAVOBJECTS_INCLUDE_NAME
//#define UAVOBJECTS_INCLUDE_METANAME


